[package]
name = "example-polars"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.26" }
pyo3-polars = { version = "0.25.0", features = ["derive", "dtype-full"] }
polars = { version = "0.52.0", features = ["dtype-full"], default-features = false }
serde = { version = "1", features = ["derive"] }

[profile.release-lto]
inherits = "release"
lto = true

[lib]
name = "_lib"
crate-type = ["cdylib"]
path = "rust/lib.rs"

[[bin]]
name = "print-hello"
path = "rust/print_hello.rs"
